function saveAdaptiveInfo(mixDir)

% Load the .mat files generated by platAdaptiveListening() in a directory
% and plot the evolution of the difficulty and the correctness over time
% for each stimulus.

[~,files] = findFiles(mixDir, '.*.mat$');
if isempty(files)
    return
end

for f = 1:length(files)
    %m = load(files{f});
    bn = basename(files{f}, 0);
    fn = ['f_' regexprep(bn(1:end-3), '[^a-zA-Z0-9_]', '')];
    num = str2double(bn(end-2:end));
    data.(fn)(num) = orderfields(load(files{f}));
end

fns = fieldnames(data);

% bps levels over blocks
bps = cat(2, data.(fns{1}).perStimBps)';

% save all bubble info
outDir = fullfile(mixDir, 'allBubbleInfo.txt')
csvwrite(outDir, bps)